export const Database = {
  public: {
    Tables: {
      tbl_auction_items: {
        Row: {
          _id : '1_|string',
          auction_item_created_at : '1_|string',
          auction_item_expires : '1_|string',
          auction_item_highest_amount : '1_|number',
          auction_item_id : '1_|number',
          auction_item_ighest_bidder : '1_|string',
          auction_item_lowest_amount : '1_|number',
          auction_item_updated_at : '1_|string',
          auction_type_id : '1_|number',
          fid : '1_|string',
          market_item_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          auction_item_created_at  : '0_|string',
          auction_item_expires  : '0_|string',
          auction_item_highest_amount  : '0_|number',
          auction_item_id  : '0_|number',
          auction_item_ighest_bidder  : '0_|string',
          auction_item_lowest_amount  : '0_|number',
          auction_item_updated_at  : '0_|string',
          auction_type_id  : '0_|number',
          fid  : '0_|string',
          market_item_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          auction_item_created_at  : '0_|string',
          auction_item_expires  : '0_|string',
          auction_item_highest_amount  : '0_|number',
          auction_item_id  : '0_|number',
          auction_item_ighest_bidder  : '0_|string',
          auction_item_lowest_amount  : '0_|number',
          auction_item_updated_at  : '0_|string',
          auction_type_id  : '0_|number',
          fid  : '0_|string',
          market_item_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_auction_items_auction_type_id_fkey",
            columns : ["auction_type_id"],
            referencedRelation : "tbl_auction_types",
            referencedColumns : ["auction_type_id"],
          },
          {
            foreignKeyName : "tbl_auction_items_market_item_id_fkey",
            columns : ["market_item_id"],
            referencedRelation : "tbl_market_items",
            referencedColumns : ["market_item_id"],
          },
        ]
      },
      tbl_auction_types: {
        Row: {
          _id : '1_|string',
          auction_type : '1_|string',
          auction_type_description : '1_|string',
          auction_type_id : '1_|number',
          fid : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          auction_type : '1_|string',
          auction_type_description  : '0_|string',
          auction_type_id  : '0_|number',
          fid  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          auction_type  : '0_|string',
          auction_type_description  : '0_|string',
          auction_type_id  : '0_|number',
          fid  : '0_|string',
        },
        Relationships : []
      },
      tbl_authors: {
        Row: {
          _id : '1_|string',
          author_created_at : '1_|string',
          author_id : '1_|number',
          author_is_active : '1_|boolean',
          author_is_verified : '1_|boolean',
          author_rating : '1_|number',
          author_sold_items : '1_|number',
          author_sold_value : '1_|any',
          author_updated_at : '1_|string',
          author_uuid : '1_|string',
          category_id : '1_|number',
          fid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          author_created_at  : '0_|string',
          author_id  : '0_|number',
          author_is_active  : '0_|boolean',
          author_is_verified  : '0_|boolean',
          author_rating  : '0_|number',
          author_sold_items  : '0_|number',
          author_sold_value  : '0_|any',
          author_updated_at  : '0_|string',
          author_uuid  : '0_|string',
          category_id  : '0_|number',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          author_created_at  : '0_|string',
          author_id  : '0_|number',
          author_is_active  : '0_|boolean',
          author_is_verified  : '0_|boolean',
          author_rating  : '0_|number',
          author_sold_items  : '0_|number',
          author_sold_value  : '0_|any',
          author_updated_at  : '0_|string',
          author_uuid  : '0_|string',
          category_id  : '0_|number',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_authors_category_id_fkey",
            columns : ["category_id"],
            referencedRelation : "tbl_categories",
            referencedColumns : ["category_id"],
          },
          {
            foreignKeyName : "tbl_authors_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_bid_status: {
        Row: {
          _id : '1_|string',
          bid_status_id : '1_|number',
          bid_status_name : '1_|string',
          fid : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          bid_status_id  : '0_|number',
          bid_status_name : '1_|string',
          fid  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          bid_status_id  : '0_|number',
          bid_status_name  : '0_|string',
          fid  : '0_|string',
        },
        Relationships : []
      },
      tbl_bid_types: {
        Row: {
          _id : '1_|string',
          bid_type : '1_|string',
          bid_type_description : '1_|string',
          bid_type_id : '1_|number',
          fid : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          bid_type : '1_|string',
          bid_type_description  : '0_|string',
          bid_type_id  : '0_|number',
          fid  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          bid_type  : '0_|string',
          bid_type_description  : '0_|string',
          bid_type_id  : '0_|number',
          fid  : '0_|string',
        },
        Relationships : []
      },
      tbl_bids: {
        Row: {
          _id : '1_|string',
          auction_item_id : '1_|number',
          bid_amount : '1_|number',
          bid_created_at : '1_|string',
          bid_id : '1_|number',
          bid_status : '1_|number',
          bid_type : '1_|number',
          bid_updated_at : '1_|string',
          bid_uuid : '1_|string',
          fid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          auction_item_id  : '0_|number',
          bid_amount  : '0_|number',
          bid_created_at  : '0_|string',
          bid_id  : '0_|number',
          bid_status  : '0_|number',
          bid_type  : '0_|number',
          bid_updated_at  : '0_|string',
          bid_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          auction_item_id  : '0_|number',
          bid_amount  : '0_|number',
          bid_created_at  : '0_|string',
          bid_id  : '0_|number',
          bid_status  : '0_|number',
          bid_type  : '0_|number',
          bid_updated_at  : '0_|string',
          bid_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_bids_auction_item_id_fkey",
            columns : ["auction_item_id"],
            referencedRelation : "tbl_auction_items",
            referencedColumns : ["auction_item_id"],
          },
          {
            foreignKeyName : "tbl_bids_bid_status_fkey",
            columns : ["bid_status"],
            referencedRelation : "tbl_bid_status",
            referencedColumns : ["bid_status_id"],
          },
          {
            foreignKeyName : "tbl_bids_bid_type_fkey",
            columns : ["bid_type"],
            referencedRelation : "tbl_bid_types",
            referencedColumns : ["bid_type_id"],
          },
          {
            foreignKeyName : "tbl_bids_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_bonuses: {
        Row: {
          _id : '1_|string',
          bonus_created_at : '1_|string',
          bonus_fb : '1_|number',
          bonus_id : '1_|number',
          bonus_ig : '1_|number',
          bonus_in : '1_|number',
          bonus_md : '1_|number',
          bonus_tg : '1_|number',
          bonus_tt : '1_|number',
          bonus_updated_at : '1_|string',
          bonus_uuid : '1_|string',
          bonus_wa : '1_|number',
          bonus_x : '1_|number',
          bonus_yt : '1_|number',
          fid : '1_|string',
          user_id : '1_|number',
          verify_email : '1_|number',
          verify_id : '1_|number',
          verify_phone : '1_|number',
          verify_residence : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          bonus_created_at  : '0_|string',
          bonus_fb  : '0_|number',
          bonus_id  : '0_|number',
          bonus_ig  : '0_|number',
          bonus_in  : '0_|number',
          bonus_md  : '0_|number',
          bonus_tg  : '0_|number',
          bonus_tt  : '0_|number',
          bonus_updated_at  : '0_|string',
          bonus_uuid  : '0_|string',
          bonus_wa  : '0_|number',
          bonus_x  : '0_|number',
          bonus_yt  : '0_|number',
          fid  : '0_|string',
          user_id  : '0_|number',
          verify_email  : '0_|number',
          verify_id  : '0_|number',
          verify_phone  : '0_|number',
          verify_residence  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          bonus_created_at  : '0_|string',
          bonus_fb  : '0_|number',
          bonus_id  : '0_|number',
          bonus_ig  : '0_|number',
          bonus_in  : '0_|number',
          bonus_md  : '0_|number',
          bonus_tg  : '0_|number',
          bonus_tt  : '0_|number',
          bonus_updated_at  : '0_|string',
          bonus_uuid  : '0_|string',
          bonus_wa  : '0_|number',
          bonus_x  : '0_|number',
          bonus_yt  : '0_|number',
          fid  : '0_|string',
          user_id  : '0_|number',
          verify_email  : '0_|number',
          verify_id  : '0_|number',
          verify_phone  : '0_|number',
          verify_residence  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_bonuses_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_categories: {
        Row: {
          _id : '1_|string',
          category_created_at : '1_|string',
          category_icon : '1_|string',
          category_id : '1_|number',
          category_is_active : '1_|boolean',
          category_name : '1_|string',
          category_parent_id : '1_|number',
          category_slug : '1_|string',
          category_updated_at : '1_|string',
          category_uuid : '1_|string',
          fid : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          category_created_at  : '0_|string',
          category_icon  : '0_|string',
          category_id  : '0_|number',
          category_is_active  : '0_|boolean',
          category_name  : '0_|string',
          category_parent_id  : '0_|number',
          category_slug  : '0_|string',
          category_updated_at  : '0_|string',
          category_uuid  : '0_|string',
          fid  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          category_created_at  : '0_|string',
          category_icon  : '0_|string',
          category_id  : '0_|number',
          category_is_active  : '0_|boolean',
          category_name  : '0_|string',
          category_parent_id  : '0_|number',
          category_slug  : '0_|string',
          category_updated_at  : '0_|string',
          category_uuid  : '0_|string',
          fid  : '0_|string',
        },
        Relationships : []
      },
      tbl_clients: {
        Row: {
          _id : '1_|string',
          client_device_created_at : '1_|string',
          client_device_id : '1_|string',
          client_device_meta : '1_|any',
          client_device_name : '1_|string',
          client_device_pub_key : '1_|string',
          client_device_secret : '1_|string',
          client_device_updated_at : '1_|string',
          client_device_uuid : '1_|string',
          client_id : '1_|number',
          fid : '1_|string',
          service_device_pub_key : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          client_device_created_at  : '0_|string',
          client_device_id  : '0_|string',
          client_device_meta  : '0_|any',
          client_device_name  : '0_|string',
          client_device_pub_key  : '0_|string',
          client_device_secret  : '0_|string',
          client_device_updated_at  : '0_|string',
          client_device_uuid  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          service_device_pub_key  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          client_device_created_at  : '0_|string',
          client_device_id  : '0_|string',
          client_device_meta  : '0_|any',
          client_device_name  : '0_|string',
          client_device_pub_key  : '0_|string',
          client_device_secret  : '0_|string',
          client_device_updated_at  : '0_|string',
          client_device_uuid  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          service_device_pub_key  : '0_|string',
        },
        Relationships : []
      },
      tbl_collections: {
        Row: {
          _id : '1_|string',
          category_id : '1_|number',
          collection_banner : '1_|string',
          collection_created_at : '1_|string',
          collection_description : '1_|string',
          collection_id : '1_|number',
          collection_name : '1_|string',
          collection_thumbnail : '1_|string',
          collection_updated_at : '1_|string',
          collection_uuid : '1_|string',
          fid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          category_id  : '0_|number',
          collection_banner  : '0_|string',
          collection_created_at  : '0_|string',
          collection_description  : '0_|string',
          collection_id  : '0_|number',
          collection_name  : '0_|string',
          collection_thumbnail  : '0_|string',
          collection_updated_at  : '0_|string',
          collection_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          category_id  : '0_|number',
          collection_banner  : '0_|string',
          collection_created_at  : '0_|string',
          collection_description  : '0_|string',
          collection_id  : '0_|number',
          collection_name  : '0_|string',
          collection_thumbnail  : '0_|string',
          collection_updated_at  : '0_|string',
          collection_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : []
      },
      tbl_engagement: {
        Row: {
          _id : '1_|string',
          engagement_claimed_off_days : '1_|number',
          engagement_consecutive_days : '1_|number',
          engagement_created_at : '1_|string',
          engagement_id : '1_|number',
          engagement_off_days : '1_|number',
          engagement_updated_at : '1_|string',
          engagement_uuid : '1_|string',
          fid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          engagement_claimed_off_days  : '0_|number',
          engagement_consecutive_days  : '0_|number',
          engagement_created_at  : '0_|string',
          engagement_id  : '0_|number',
          engagement_off_days  : '0_|number',
          engagement_updated_at  : '0_|string',
          engagement_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          engagement_claimed_off_days  : '0_|number',
          engagement_consecutive_days  : '0_|number',
          engagement_created_at  : '0_|string',
          engagement_id  : '0_|number',
          engagement_off_days  : '0_|number',
          engagement_updated_at  : '0_|string',
          engagement_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_engagement_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_favourite_collections: {
        Row: {
          _id : '1_|string',
          collection_id : '1_|number',
          favourite_collection_created_at : '1_|string',
          favourite_collection_id : '1_|number',
          favourite_collection_updated_at : '1_|string',
          favourite_collection_uuid : '1_|string',
          fid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          collection_id  : '0_|number',
          favourite_collection_created_at  : '0_|string',
          favourite_collection_id  : '0_|number',
          favourite_collection_updated_at  : '0_|string',
          favourite_collection_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          collection_id  : '0_|number',
          favourite_collection_created_at  : '0_|string',
          favourite_collection_id  : '0_|number',
          favourite_collection_updated_at  : '0_|string',
          favourite_collection_uuid  : '0_|string',
          fid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_favourite_collections_collection_id_fkey",
            columns : ["collection_id"],
            referencedRelation : "tbl_collections",
            referencedColumns : ["collection_id"],
          },
          {
            foreignKeyName : "tbl_favourite_collections_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_invite_links: {
        Row: {
          _id : '1_|string',
          fid : '1_|string',
          link : '1_|string',
          link_created_at : '1_|string',
          link_expires : '1_|string',
          link_id : '1_|number',
          link_updated_at : '1_|string',
          link_uuid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          fid  : '0_|string',
          link  : '0_|string',
          link_created_at  : '0_|string',
          link_expires  : '0_|string',
          link_id  : '0_|number',
          link_updated_at  : '0_|string',
          link_uuid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          fid  : '0_|string',
          link  : '0_|string',
          link_created_at  : '0_|string',
          link_expires  : '0_|string',
          link_id  : '0_|number',
          link_updated_at  : '0_|string',
          link_uuid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_invite_links_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_invite_users: {
        Row: {
          _id : '1_|string',
          fid : '1_|string',
          invite_created_at : '1_|string',
          invite_from : '1_|number',
          invite_id : '1_|number',
          invite_reward : '1_|number',
          invite_to : '1_|number',
          invite_updated_at : '1_|string',
          invite_uuid : '1_|string',
          link_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          fid  : '0_|string',
          invite_created_at  : '0_|string',
          invite_from  : '0_|number',
          invite_id  : '0_|number',
          invite_reward  : '0_|number',
          invite_to  : '0_|number',
          invite_updated_at  : '0_|string',
          invite_uuid  : '0_|string',
          link_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          fid  : '0_|string',
          invite_created_at  : '0_|string',
          invite_from  : '0_|number',
          invite_id  : '0_|number',
          invite_reward  : '0_|number',
          invite_to  : '0_|number',
          invite_updated_at  : '0_|string',
          invite_uuid  : '0_|string',
          link_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_invite_users_invite_from_fkey",
            columns : ["invite_from"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
          {
            foreignKeyName : "tbl_invite_users_invite_to_fkey",
            columns : ["invite_to"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
          {
            foreignKeyName : "tbl_invite_users_link_id_fkey",
            columns : ["link_id"],
            referencedRelation : "tbl_invite_links",
            referencedColumns : ["link_id"],
          },
        ]
      },
      tbl_login_sessions: {
        Row: {
          _id : '1_|string',
          client_id : '1_|number',
          fid : '1_|string',
          session_created_at : '1_|string',
          session_ended_at : '1_|string',
          session_id : '1_|number',
          session_updated_at : '1_|string',
          session_uuid : '1_|string',
          socket_io : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          session_created_at  : '0_|string',
          session_ended_at  : '0_|string',
          session_id  : '0_|number',
          session_updated_at  : '0_|string',
          session_uuid  : '0_|string',
          socket_io  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          session_created_at  : '0_|string',
          session_ended_at  : '0_|string',
          session_id  : '0_|number',
          session_updated_at  : '0_|string',
          session_uuid  : '0_|string',
          socket_io  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_login_sessions_client_id_fkey",
            columns : ["client_id"],
            referencedRelation : "tbl_clients",
            referencedColumns : ["client_id"],
          },
          {
            foreignKeyName : "tbl_login_sessions_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_market_items: {
        Row: {
          _id : '1_|string',
          auction_item_id : '1_|number',
          category_id : '1_|number',
          chain_id : '1_|number',
          fid : '1_|string',
          is_archived : '1_|boolean',
          is_auction : '1_|boolean',
          is_listed : '1_|boolean',
          is_sold : '1_|boolean',
          likes_count : '1_|number',
          market_item_created_at : '1_|string',
          market_item_featured : '1_|boolean',
          market_item_id : '1_|number',
          market_item_tags : '1_|string',
          market_item_updated_at : '1_|string',
          market_item_uuid : '1_|string',
          market_item_verified : '1_|boolean',
          on_chain : '1_|boolean',
          platform_fee_paid : '1_|number',
          supports_royalties : '1_|boolean',
          token_contract_address : '1_|string',
          token_creator : '1_|string',
          token_currency : '1_|string',
          token_id : '1_|number',
          token_index_id : '1_|number',
          token_interface_id : '1_|string',
          token_owner : '1_|string',
          token_price : '1_|number',
          token_seller : '1_|string',
          user_id : '1_|number',
          views_count : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          auction_item_id  : '0_|number',
          category_id  : '0_|number',
          chain_id  : '0_|number',
          fid  : '0_|string',
          is_archived  : '0_|boolean',
          is_auction  : '0_|boolean',
          is_listed  : '0_|boolean',
          is_sold  : '0_|boolean',
          likes_count  : '0_|number',
          market_item_created_at  : '0_|string',
          market_item_featured  : '0_|boolean',
          market_item_id  : '0_|number',
          market_item_tags  : '0_|string',
          market_item_updated_at  : '0_|string',
          market_item_uuid  : '0_|string',
          market_item_verified  : '0_|boolean',
          on_chain  : '0_|boolean',
          platform_fee_paid  : '0_|number',
          supports_royalties  : '0_|boolean',
          token_contract_address  : '0_|string',
          token_creator  : '0_|string',
          token_currency  : '0_|string',
          token_id  : '0_|number',
          token_index_id  : '0_|number',
          token_interface_id  : '0_|string',
          token_owner  : '0_|string',
          token_price  : '0_|number',
          token_seller  : '0_|string',
          user_id  : '0_|number',
          views_count  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          auction_item_id  : '0_|number',
          category_id  : '0_|number',
          chain_id  : '0_|number',
          fid  : '0_|string',
          is_archived  : '0_|boolean',
          is_auction  : '0_|boolean',
          is_listed  : '0_|boolean',
          is_sold  : '0_|boolean',
          likes_count  : '0_|number',
          market_item_created_at  : '0_|string',
          market_item_featured  : '0_|boolean',
          market_item_id  : '0_|number',
          market_item_tags  : '0_|string',
          market_item_updated_at  : '0_|string',
          market_item_uuid  : '0_|string',
          market_item_verified  : '0_|boolean',
          on_chain  : '0_|boolean',
          platform_fee_paid  : '0_|number',
          supports_royalties  : '0_|boolean',
          token_contract_address  : '0_|string',
          token_creator  : '0_|string',
          token_currency  : '0_|string',
          token_id  : '0_|number',
          token_index_id  : '0_|number',
          token_interface_id  : '0_|string',
          token_owner  : '0_|string',
          token_price  : '0_|number',
          token_seller  : '0_|string',
          user_id  : '0_|number',
          views_count  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_market_items_auction_item_id_fkey",
            columns : ["auction_item_id"],
            referencedRelation : "tbl_auction_items",
            referencedColumns : ["auction_item_id"],
          },
          {
            foreignKeyName : "tbl_market_items_category_id_fkey",
            columns : ["category_id"],
            referencedRelation : "tbl_categories",
            referencedColumns : ["category_id"],
          },
          {
            foreignKeyName : "tbl_market_items_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_mining_sessions: {
        Row: {
          _id : '1_|string',
          client_id : '1_|number',
          fid : '1_|string',
          mining_base_rate : '1_|number',
          mining_booster : '1_|number',
          mining_chain_id : '1_|number',
          mining_claim_hash : '1_|string',
          mining_claimed : '1_|boolean',
          mining_ended_at : '1_|string',
          mining_id : '1_|number',
          mining_rate : '1_|number',
          mining_started_at : '1_|string',
          mining_uuid : '1_|string',
          mining_wallet_address : '1_|string',
          session_id : '1_|number',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          mining_base_rate  : '0_|number',
          mining_booster  : '0_|number',
          mining_chain_id  : '0_|number',
          mining_claim_hash  : '0_|string',
          mining_claimed  : '0_|boolean',
          mining_ended_at  : '0_|string',
          mining_id  : '0_|number',
          mining_rate  : '0_|number',
          mining_started_at  : '0_|string',
          mining_uuid  : '0_|string',
          mining_wallet_address  : '0_|string',
          session_id  : '0_|number',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          client_id  : '0_|number',
          fid  : '0_|string',
          mining_base_rate  : '0_|number',
          mining_booster  : '0_|number',
          mining_chain_id  : '0_|number',
          mining_claim_hash  : '0_|string',
          mining_claimed  : '0_|boolean',
          mining_ended_at  : '0_|string',
          mining_id  : '0_|number',
          mining_rate  : '0_|number',
          mining_started_at  : '0_|string',
          mining_uuid  : '0_|string',
          mining_wallet_address  : '0_|string',
          session_id  : '0_|number',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_mining_sessions_client_id_fkey",
            columns : ["client_id"],
            referencedRelation : "tbl_clients",
            referencedColumns : ["client_id"],
          },
          {
            foreignKeyName : "tbl_mining_sessions_session_id_fkey",
            columns : ["session_id"],
            referencedRelation : "tbl_login_sessions",
            referencedColumns : ["session_id"],
          },
          {
            foreignKeyName : "tbl_mining_sessions_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_nft_logs: {
        Row: {
          _id : '1_|string',
          fid : '1_|string',
          log_amount : '1_|number',
          log_chain_id : '1_|number',
          log_data : '1_|any',
          log_from : '1_|string',
          log_id : '1_|number',
          log_nft_created_at : '1_|string',
          log_to : '1_|string',
          log_txn_hash : '1_|string',
          log_type : '1_|string',
          log_uuid : '1_|string',
          nft_id : '1_|number',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          fid  : '0_|string',
          log_amount  : '0_|number',
          log_chain_id  : '0_|number',
          log_data  : '0_|any',
          log_from  : '0_|string',
          log_id  : '0_|number',
          log_nft_created_at  : '0_|string',
          log_to  : '0_|string',
          log_txn_hash  : '0_|string',
          log_type  : '0_|string',
          log_uuid  : '0_|string',
          nft_id  : '0_|number',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          fid  : '0_|string',
          log_amount  : '0_|number',
          log_chain_id  : '0_|number',
          log_data  : '0_|any',
          log_from  : '0_|string',
          log_id  : '0_|number',
          log_nft_created_at  : '0_|string',
          log_to  : '0_|string',
          log_txn_hash  : '0_|string',
          log_type  : '0_|string',
          log_uuid  : '0_|string',
          nft_id  : '0_|number',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_nft_logs_nft_id_fkey",
            columns : ["nft_id"],
            referencedRelation : "tbl_nfts",
            referencedColumns : ["nft_id"],
          },
          {
            foreignKeyName : "tbl_nft_logs_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_nft_ranking: {
        Row: {
          _id : '1_|string',
          author_id : '1_|number',
          collection_id : '1_|number',
          fid : '1_|string',
          nft_id : '1_|number',
          nft_rank : '1_|number',
          nft_ranking_created_at : '1_|string',
          nft_ranking_d14d : '1_|number',
          nft_ranking_d21d : '1_|number',
          nft_ranking_d24hr : '1_|number',
          nft_ranking_d28 : '1_|number',
          nft_ranking_d7d : '1_|number',
          nft_ranking_floor_price : '1_|number',
          nft_ranking_id : '1_|number',
          nft_ranking_items : '1_|number',
          nft_ranking_owners : '1_|number',
          nft_ranking_updated_at : '1_|number',
          nft_ranking_uuid : '1_|string',
          nft_ranking_volume : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          author_id  : '0_|number',
          collection_id  : '0_|number',
          fid  : '0_|string',
          nft_id  : '0_|number',
          nft_rank  : '0_|number',
          nft_ranking_created_at  : '0_|string',
          nft_ranking_d14d  : '0_|number',
          nft_ranking_d21d  : '0_|number',
          nft_ranking_d24hr  : '0_|number',
          nft_ranking_d28  : '0_|number',
          nft_ranking_d7d  : '0_|number',
          nft_ranking_floor_price  : '0_|number',
          nft_ranking_id  : '0_|number',
          nft_ranking_items  : '0_|number',
          nft_ranking_owners  : '0_|number',
          nft_ranking_updated_at  : '0_|number',
          nft_ranking_uuid  : '0_|string',
          nft_ranking_volume  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          author_id  : '0_|number',
          collection_id  : '0_|number',
          fid  : '0_|string',
          nft_id  : '0_|number',
          nft_rank  : '0_|number',
          nft_ranking_created_at  : '0_|string',
          nft_ranking_d14d  : '0_|number',
          nft_ranking_d21d  : '0_|number',
          nft_ranking_d24hr  : '0_|number',
          nft_ranking_d28  : '0_|number',
          nft_ranking_d7d  : '0_|number',
          nft_ranking_floor_price  : '0_|number',
          nft_ranking_id  : '0_|number',
          nft_ranking_items  : '0_|number',
          nft_ranking_owners  : '0_|number',
          nft_ranking_updated_at  : '0_|number',
          nft_ranking_uuid  : '0_|string',
          nft_ranking_volume  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_nft_ranking_author_id_fkey",
            columns : ["author_id"],
            referencedRelation : "tbl_authors",
            referencedColumns : ["author_id"],
          },
          {
            foreignKeyName : "tbl_nft_ranking_collection_id_fkey",
            columns : ["collection_id"],
            referencedRelation : "tbl_collections",
            referencedColumns : ["collection_id"],
          },
          {
            foreignKeyName : "tbl_nft_ranking_nft_id_fkey",
            columns : ["nft_id"],
            referencedRelation : "tbl_nfts",
            referencedColumns : ["nft_id"],
          },
        ]
      },
      tbl_nfts: {
        Row: {
          _id : '1_|string',
          category_id : '1_|number',
          fid : '1_|string',
          nft_address : '1_|string',
          nft_auction_meta : '1_|any',
          nft_chains : '1_|any',
          nft_collection_meta : '1_|any',
          nft_created_at : '1_|string',
          nft_description : '1_|string',
          nft_gallery : '1_|any',
          nft_hash : '1_|string',
          nft_id : '1_|number',
          nft_interface_id : '1_|string',
          nft_interface_type : '1_|string',
          nft_ipfs_id : '1_|string',
          nft_is_auction : '1_|boolean',
          nft_link : '1_|string',
          nft_meta : '1_|any',
          nft_minted : '1_|boolean',
          nft_name : '1_|string',
          nft_preview : '1_|string',
          nft_price : '1_|number',
          nft_pricing : '1_|any',
          nft_properties : '1_|any',
          nft_royalty_amount : '1_|number',
          nft_royalty_receiver : '1_|string',
          nft_sensitive_content : '1_|boolean',
          nft_supply : '1_|number',
          nft_support_royalties : '1_|boolean',
          nft_symbol : '1_|string',
          nft_unlockable : '1_|boolean',
          nft_updated_at : '1_|string',
          nft_uuid : '1_|string',
          token_creator : '1_|string',
          token_id : '1_|number',
          token_minter : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          category_id  : '0_|number',
          fid  : '0_|string',
          nft_address  : '0_|string',
          nft_auction_meta  : '0_|any',
          nft_chains  : '0_|any',
          nft_collection_meta  : '0_|any',
          nft_created_at  : '0_|string',
          nft_description  : '0_|string',
          nft_gallery  : '0_|any',
          nft_hash  : '0_|string',
          nft_id  : '0_|number',
          nft_interface_id  : '0_|string',
          nft_interface_type  : '0_|string',
          nft_ipfs_id  : '0_|string',
          nft_is_auction  : '0_|boolean',
          nft_link  : '0_|string',
          nft_meta  : '0_|any',
          nft_minted  : '0_|boolean',
          nft_name  : '0_|string',
          nft_preview  : '0_|string',
          nft_price  : '0_|number',
          nft_pricing  : '0_|any',
          nft_properties  : '0_|any',
          nft_royalty_amount  : '0_|number',
          nft_royalty_receiver  : '0_|string',
          nft_sensitive_content  : '0_|boolean',
          nft_supply  : '0_|number',
          nft_support_royalties  : '0_|boolean',
          nft_symbol  : '0_|string',
          nft_unlockable  : '0_|boolean',
          nft_updated_at  : '0_|string',
          nft_uuid  : '0_|string',
          token_creator  : '0_|string',
          token_id  : '0_|number',
          token_minter  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          category_id  : '0_|number',
          fid  : '0_|string',
          nft_address  : '0_|string',
          nft_auction_meta  : '0_|any',
          nft_chains  : '0_|any',
          nft_collection_meta  : '0_|any',
          nft_created_at  : '0_|string',
          nft_description  : '0_|string',
          nft_gallery  : '0_|any',
          nft_hash  : '0_|string',
          nft_id  : '0_|number',
          nft_interface_id  : '0_|string',
          nft_interface_type  : '0_|string',
          nft_ipfs_id  : '0_|string',
          nft_is_auction  : '0_|boolean',
          nft_link  : '0_|string',
          nft_meta  : '0_|any',
          nft_minted  : '0_|boolean',
          nft_name  : '0_|string',
          nft_preview  : '0_|string',
          nft_price  : '0_|number',
          nft_pricing  : '0_|any',
          nft_properties  : '0_|any',
          nft_royalty_amount  : '0_|number',
          nft_royalty_receiver  : '0_|string',
          nft_sensitive_content  : '0_|boolean',
          nft_supply  : '0_|number',
          nft_support_royalties  : '0_|boolean',
          nft_symbol  : '0_|string',
          nft_unlockable  : '0_|boolean',
          nft_updated_at  : '0_|string',
          nft_uuid  : '0_|string',
          token_creator  : '0_|string',
          token_id  : '0_|number',
          token_minter  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_nfts_category_id_fkey",
            columns : ["category_id"],
            referencedRelation : "tbl_categories",
            referencedColumns : ["category_id"],
          },
          {
            foreignKeyName : "tbl_nfts_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_options: {
        Row: {
          _id : '1_|string',
          fid : '1_|string',
          option_created_at : '1_|string',
          option_datatype : '1_|string',
          option_id : '1_|number',
          option_slug : '1_|string',
          option_updated_at : '1_|string',
          option_uuid : '1_|string',
          option_value : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          fid  : '0_|string',
          option_created_at  : '0_|string',
          option_datatype  : '0_|string',
          option_id  : '0_|number',
          option_slug  : '0_|string',
          option_updated_at  : '0_|string',
          option_uuid  : '0_|string',
          option_value  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          fid  : '0_|string',
          option_created_at  : '0_|string',
          option_datatype  : '0_|string',
          option_id  : '0_|number',
          option_slug  : '0_|string',
          option_updated_at  : '0_|string',
          option_uuid  : '0_|string',
          option_value  : '0_|string',
        },
        Relationships : []
      },
      tbl_user_collections: {
        Row: {
          _id : '1_|string',
          collection_id : '1_|number',
          fid : '1_|string',
          user_collection_created_at : '1_|string',
          user_collection_id : '1_|number',
          user_collection_updated_at : '1_|string',
          user_collection_uuid : '1_|string',
          user_id : '1_|number',
        },
        Insert: {
          _id  : '0_|string',
          collection_id  : '0_|number',
          fid  : '0_|string',
          user_collection_created_at  : '0_|string',
          user_collection_id  : '0_|number',
          user_collection_updated_at  : '0_|string',
          user_collection_uuid  : '0_|string',
          user_id  : '0_|number',
        },
        Update: {
          _id  : '0_|string',
          collection_id  : '0_|number',
          fid  : '0_|string',
          user_collection_created_at  : '0_|string',
          user_collection_id  : '0_|number',
          user_collection_updated_at  : '0_|string',
          user_collection_uuid  : '0_|string',
          user_id  : '0_|number',
        },
        Relationships : [
          {
            foreignKeyName : "tbl_user_collections_collection_id_fkey",
            columns : ["collection_id"],
            referencedRelation : "tbl_collections",
            referencedColumns : ["collection_id"],
          },
          {
            foreignKeyName : "tbl_user_collections_user_id_fkey",
            columns : ["user_id"],
            referencedRelation : "tbl_users",
            referencedColumns : ["user_id"],
          },
        ]
      },
      tbl_users: {
        Row: {
          _id : '1_|string',
          email : '1_|string',
          email_verified : '1_|boolean',
          fid : '1_|string',
          firebase_provider_data : '1_|any',
          first_name : '1_|string',
          last_name : '1_|string',
          organization_id : '1_|number',
          password : '1_|string',
          phone_number : '1_|string',
          phone_number_verified : '1_|string',
          photo_url : '1_|string',
          socket_id : '1_|string',
          supabase_provider : '1_|any',
          user_access_levels : '1_|any',
          user_country : '1_|string',
          user_created_at : '1_|string',
          user_default_role : '1_|string',
          user_dob : '1_|string',
          user_gender : '1_|string',
          user_id : '1_|number',
          user_is_active : '1_|boolean',
          user_last_login : '1_|string',
          user_last_seen : '1_|string',
          user_updated_at : '1_|string',
          user_uuid : '1_|string',
          username : '1_|string',
        },
        Insert: {
          _id  : '0_|string',
          email : '1_|string',
          email_verified  : '0_|boolean',
          fid  : '0_|string',
          firebase_provider_data  : '0_|any',
          first_name  : '0_|string',
          last_name  : '0_|string',
          organization_id  : '0_|number',
          password  : '0_|string',
          phone_number  : '0_|string',
          phone_number_verified  : '0_|string',
          photo_url  : '0_|string',
          socket_id  : '0_|string',
          supabase_provider  : '0_|any',
          user_access_levels  : '0_|any',
          user_country  : '0_|string',
          user_created_at : '1_|string',
          user_default_role  : '0_|string',
          user_dob  : '0_|string',
          user_gender  : '0_|string',
          user_id  : '0_|number',
          user_is_active  : '0_|boolean',
          user_last_login  : '0_|string',
          user_last_seen  : '0_|string',
          user_updated_at  : '0_|string',
          user_uuid  : '0_|string',
          username  : '0_|string',
        },
        Update: {
          _id  : '0_|string',
          email  : '0_|string',
          email_verified  : '0_|boolean',
          fid  : '0_|string',
          firebase_provider_data  : '0_|any',
          first_name  : '0_|string',
          last_name  : '0_|string',
          organization_id  : '0_|number',
          password  : '0_|string',
          phone_number  : '0_|string',
          phone_number_verified  : '0_|string',
          photo_url  : '0_|string',
          socket_id  : '0_|string',
          supabase_provider  : '0_|any',
          user_access_levels  : '0_|any',
          user_country  : '0_|string',
          user_created_at  : '0_|string',
          user_default_role  : '0_|string',
          user_dob  : '0_|string',
          user_gender  : '0_|string',
          user_id  : '0_|number',
          user_is_active  : '0_|boolean',
          user_last_login  : '0_|string',
          user_last_seen  : '0_|string',
          user_updated_at  : '0_|string',
          user_uuid  : '0_|string',
          username  : '0_|string',
        },
        Relationships : []
      },
    },
    Views: {
      foo: 'bar'
    },
    Functions: {
      foo: 'bar'
    },
    Enums: {
      foo: 'bar'
    },
    CompositeTypes: {
      foo: 'bar'
    },
  },
}

//END_TYPES